services:
  nginx:
    runtime: runc 
    image: nginx:latest
    container_name: ${STACK_NAME}_nginx
    restart: always
    # ports:
    #   - "${HOST_IP}:${WEB_PORT}:${WEB_PORT}"
    #   - "${HOST_IP}:${WEBS_PORT}:${WEBS_PORT}"
    volumes:
      - ${STACK_SRC}:/var/www/html
      - ./config/fpm/nginx/default.conf:/tmp/default.conf
      - ${STACK_VOLUME}/wordpress/certbot/www/:/var/www/certbot/:rw
      - ${STACK_VOLUME}/wordpress/certbot/conf/:/etc/letsencrypt/:rw
      - ./config/fpm/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
    networks:
      - fpm_network
      - traefik_overlay
    entrypoint: |
      sh -c "
        cp /tmp/default.conf /etc/nginx/conf.d/default.conf && \
        sed -i -e 's/yourdomain.com/${DOMAIN}/g' /etc/nginx/conf.d/default.conf && \
        sed -i -e 's/listen 80;/listen ${WEB_PORT};/g' /etc/nginx/conf.d/default.conf && \
        sed -i -e 's/listen 443/listen ${WEBS_PORT}/g' /etc/nginx/conf.d/default.conf && \
        sed -i -e 's/listen [::]:/listen [::]:${WEBS_PORT}/g' /etc/nginx/conf.d/default.conf && \
        sed -i -e 's/fastcgi_pass web:9000/fastcgi_pass ${STACK_NAME}_web:9000/g' /etc/nginx/conf.d/default.conf && \
        nginx -g 'daemon off;'
      "
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.${STACK_NAME}_web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${STACK_NAME}_web.service=${STACK_NAME}_web_serv"
      - "traefik.http.services.${STACK_NAME}_web_serv.loadbalancer.server.port=80"
      - "traefik.http.services.${STACK_NAME}_web_serv.loadbalancer.server.scheme=http"
      - "traefik.http.routers.${STACK_NAME}_web.entrypoints=web"

      - "traefik.http.routers.${STACK_NAME}_webs.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${STACK_NAME}_webs.service=${STACK_NAME}_webs_serv"
      - "traefik.http.services.${STACK_NAME}_webs_serv.loadbalancer.server.port=443"
      - "traefik.http.services.${STACK_NAME}_webs_serv.loadbalancer.server.scheme=https"
      - "traefik.http.routers.${STACK_NAME}_webs.entrypoints=webs"
      - "traefik.http.routers.${STACK_NAME}_webs.tls=true"
      # - "traefik.http.routers.${STACK_NAME}_webs.tls.certresolver=cloudflare"
      - "traefik.http.routers.${STACK_NAME}_webs.tls.domains[0].main=${SECOND_AND_TOP_LEVEL_DOMAIN}"
      - "traefik.http.routers.${STACK_NAME}_webs.tls.domains[0].sans=*.${SECOND_AND_TOP_LEVEL_DOMAIN}"
networks:
  fpm_network:
    external: true
    name: ${STACK_NAME}_fpm_network
  traefik_overlay:
    external: true
