services:

  web:
    runtime: runc 
    image: ${REPO}:php${IMAGE_PHP_VERSION}-${WEBSERVER}
    container_name: ${STACK_NAME}_web
    restart: always
    # ports:
    #   - "${HOST_IP}:${WEB_PORT}:${WEB_PORT}"
    #   - "${HOST_IP}:${WEBS_PORT}:${WEBS_PORT}"
    environment:
      - DOMAIN=${DOMAIN}
      - WEB_PORT=${WEB_PORT}
      - WEBS_PORT=${WEBS_PORT}
      - CERT_COUNTRY=${CERT_COUNTRY}
      - CERT_STATE=${CERT_STATE}
      - CERT_CITY=${CERT_CITY}
      - CERT_ORG=${CERT_ORG}
      - CERT_ORG_UNIT=${CERT_ORG_UNIT}
      - TZ=${TZ}

      - WORDPRESS_DB_HOST=${STACK_NAME}_db
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${DB_PREFIX}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
      - WORDPRESS_CONFIG_EXTRA=require_once ABSPATH . 'config.extra.php';
    volumes:
      - ${STACK_SRC}:/var/www/html
      - ./config/wp/config.extra.php:/var/www/html/config.extra.php:ro
      - ${STACK_VOLUME}/wordpress/certbot/www//:/var/www/certbot/:rw
      - ${STACK_VOLUME}/wordpress/certbot/conf/:/etc/letsencrypt/:rw
      - ./config/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
    networks:
      - wordpress_network
      - wp_cli_network
      - certbot_network
      - traefik_overlay
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.${STACK_NAME}_web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${STACK_NAME}_web.service=${STACK_NAME}_web_serv"
      - "traefik.http.services.${STACK_NAME}_web_serv.loadbalancer.server.port=80"
      - "traefik.http.services.${STACK_NAME}_web_serv.loadbalancer.server.scheme=http"
      - "traefik.http.routers.${STACK_NAME}_web.entrypoints=web"

      - "traefik.http.routers.${STACK_NAME}_webs.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${STACK_NAME}_webs.service=${STACK_NAME}_webs_serv"
      - "traefik.http.services.${STACK_NAME}_webs_serv.loadbalancer.server.port=443"
      - "traefik.http.services.${STACK_NAME}_webs_serv.loadbalancer.server.scheme=https"
      - "traefik.http.routers.${STACK_NAME}_webs.entrypoints=webs"
      - "traefik.http.routers.${STACK_NAME}_webs.tls=true"
      # - "traefik.http.routers.${STACK_NAME}_webs.tls.certresolver=cloudflare"
      - "traefik.http.routers.${STACK_NAME}_webs.tls.domains[0].main=${SECOND_AND_TOP_LEVEL_DOMAIN}"
      - "traefik.http.routers.${STACK_NAME}_webs.tls.domains[0].sans=*.${SECOND_AND_TOP_LEVEL_DOMAIN}"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  certbot:
    runtime: runc
    image: certbot/certbot:latest
    container_name: ${STACK_NAME}_certbot
    restart: always
    networks:
      - certbot_network
    depends_on:
      - web
    volumes:
      - ${STACK_VOLUME}/wordpress/certbot/www/:/var/www/certbot/:rw
      - ${STACK_VOLUME}/wordpress/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  db:
    runtime: runc
    image: mariadb:10.6
    container_name: ${STACK_NAME}_db
    restart: always
    # ports:
    #   - "${MARIADB_DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${STACK_VOLUME}/mysql/data:/var/lib/mysql
    networks:
      - wordpress_network
      - wp_cli_network
      - pma_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  pma:
    runtime: runc
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK_NAME}_pma
    restart: always
    # ports:
    #   - "${HOST_IP}:${PMA_PORT}:80"
    #   - "${HOST_IP}:${PMAS_PORT}:443"
    environment:
      - PMA_HOST=${STACK_NAME}_db

      # Careful: Uncomment these will expose your phpmyadmin login.
      # - PMA_USER=${DB_USER}
      # - PMA_PASSWORD=${DB_PASSWORD}
      # - PMA_DATABASE=${DB_NAME}
      # - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: >
      sh -c "sed 's|/etc/ssl/certs/ssl-cert-snakeoil.pem|/etc/letsencrypt/live/${DOMAIN}/fullchain.pem|g' /etc/apache2/sites-available/default-ssl.conf > /tmp/default-ssl.conf &&
            sed -i 's|/etc/ssl/private/ssl-cert-snakeoil.key|/etc/letsencrypt/live/${DOMAIN}/privkey.pem|g' /tmp/default-ssl.conf &&
            mv /tmp/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf &&
            a2enmod ssl &&
            a2ensite default-ssl &&
            if [ ! -f /etc/phpmyadmin/config.secret.inc.php ]; then
              echo \"<?php\\n\\\$$cfg['blowfish_secret'] = '$(php -r 'echo bin2hex(random_bytes(32));')';\" > /etc/phpmyadmin/config.secret.inc.php;
            fi && 
            apache2ctl -D FOREGROUND &
            while true; do
                sleep 12h
                apache2ctl graceful
            done
        "
    depends_on:
      - db
    networks:
      - pma_network
      - traefik_overlay
    volumes:
      - ${STACK_VOLUME}/wordpress/certbot/conf/:/etc/letsencrypt/:ro
      - ${STACK_VOLUME}/wordpress/certbot/conf/live/${DOMAIN}/fullchain.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro
      - ${STACK_VOLUME}/wordpress/certbot/conf/live/${DOMAIN}/privkey.pem:/etc/ssl/private/ssl-cert-snakeoil.key:ro
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.${STACK_NAME}_pma.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${STACK_NAME}_pma.service=${STACK_NAME}_pma_serv"
      - "traefik.http.services.${STACK_NAME}_pma_serv.loadbalancer.server.port=80"
      - "traefik.http.routers.${STACK_NAME}_pma.entrypoints=pma"

      - "traefik.http.routers.${STACK_NAME}_pmas.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${STACK_NAME}_pmas.service=${STACK_NAME}_pmas_serv"
      - "traefik.http.services.${STACK_NAME}_pmas_serv.loadbalancer.server.port=443"
      - "traefik.http.services.${STACK_NAME}_pmas_serv.loadbalancer.server.scheme=https"
      - "traefik.http.routers.${STACK_NAME}_pmas.entrypoints=pmas"
      - "traefik.http.routers.${STACK_NAME}_pmas.tls=true"
      # - "traefik.http.routers.${STACK_NAME}_aaps.tls.certresolver=cloudflare"
      - "traefik.http.routers.${STACK_NAME}_pmas.tls.domains[0].main=${SECOND_AND_TOP_LEVEL_DOMAIN}"
      - "traefik.http.routers.${STACK_NAME}_pmas.tls.domains[0].sans=*.${SECOND_AND_TOP_LEVEL_DOMAIN}"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
networks:
  wordpress_network:
    name: ${STACK_NAME}_network
  wp_cli_network:
    external: true
    name: ${STACK_NAME}_cli_network
  pma_network:
  certbot_network:
  traefik_overlay:
    external: true
  